apiVersion: v1
kind: ConfigMap
metadata:
  name: skupper-site
  namespace: east
data:
  name: east-site

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
  annotations:
    skupper.io/proxy: tcp
  namespace: east
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: quay.io/skupper/hello-world-backend
          ports:
            - containerPort: 8080

