apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: skupper-og
  namespace: skupper-operator-v2
spec:
  upgradeStrategy: Default

---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/skupper-operator.skupper-operator-2: ''
  name: skupper-operator-v2
  namespace: skupper-operator-v2
spec:
  channel: stable-2
  installPlanApproval: Automatic
  name: skupper-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
