apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: skupper-og
  namespace: skupper-operator-v1
spec:
  upgradeStrategy: Default

---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/skupper-operator.skupper-operator-1: ""
  name: skupper-operator-v1
  namespace: skupper-operator-v1
spec:
  channel: stable-1.9
  installPlanApproval: Automatic
  name: skupper-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace

