apiVersion: v1
kind: ConfigMap
metadata:
  name: skupper-site
  namespace: west
data:
  name: west-site

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
  namespace: west
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: quay.io/skupper/hello-world-frontend
          ports:
            - containerPort: 8080


